name: aws
authore: SooYoung
description: "Use aws module int github action"
inputs:
  AWS_REGION:
    description: "set aws region"
    required: true
    default: "ap-northeast-2"
  AWS_ROLE_TO_ASSUME:
    description: "set aws role to assume"
    required: true
    default: "GithubActions"

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      id: credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.AWS_REGION }}
        role-to-assume: ${{ intputs.AWS_ROLE_TO_ASSUME }}
